### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by 0sujaljain0** [sujalcodes3/Vivacity_2k24#122]
- [x] Home Page Explore Events Button
- [x] Home Page  Register Button
- [x] Scroll To Top
- [x] Hamsburger Vivacity logo
- [x] Data, Data Everywhere Data
